### ISSUE TITLE
Need Help using Minimax

### ISSUE THREAD

**Issue by kdridi** [Manwe56/competitive-programming#11]
I'm trying to use Minimax class with a simple Nim game (wikipedia ref below).

The principle is quite simple : it a two player game, each player has to remove between 1 and "max" matches on a a single line. The player who removes the last match has lost the game.

Here is my game using this project.
https://gist.github.com/kdridi/eeab9c28378b52a646fe11a65a46b7ea

I get an exception due to a cancellable move.

When you run Minimax.evaluateSubPossibilities, you try on line cancel a move (line 148) on a "game" that has not been created by this "move". The "move" has generated "movedGame" on line 121 but not the "game" instance.

https://en.wikipedia.org/wiki/Nim
https://fr.wikipedia.org/wiki/Jeu_de_Marienbad

**Comment by Manwe56** [comment]
Your analysis is correct, this is a bug, and in all the lines between 121 and 148, movedGame should be used instead of game.
For performance reason, I usually use the same instance of the game to avoid having to duplicate the instance each time I need to navigate in the game tree, that's why I never faced the issue. This require to be able to write the reverse of your move, but can dramatically increase the depth up to which your bot will be able to go :). Same issue is present in C++...

**Comment by Manwe56** [comment]
Should be fixed by 4f92a09
